#!/usr/bin/env bash
# Start (or stop) the Paperclip that No Hands delegates to. One command.
#
#   ./Scripts/paperclip/up.sh            start in the background (first run writes .env)
#   ./Scripts/paperclip/up.sh down       stop
#   ./Scripts/paperclip/up.sh logs       follow the log
#   ./Scripts/paperclip/up.sh status
#
# Default engine is the official npm package (`npx paperclipai run`), the same
# quickstart Paperclip documents; it needs Node 20+ and nothing else. Set
# PAPERCLIP_ENGINE=docker to build and run the container from a Paperclip
# checkout instead (PAPERCLIP_SRC, default ../../../paperclip).
#
# Runs in local trusted mode on 127.0.0.1:3100 — no login, nothing exposed.
# Data lives under Scripts/paperclip/data (git-ignored).
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"
PORT="${PAPERCLIP_PORT:-3100}"
ENGINE="${PAPERCLIP_ENGINE:-npx}"
PIDFILE="$HERE/data/paperclip.pid"
LOG="$HERE/data/paperclip.log"
mkdir -p "$HERE/data"

if [ ! -f .env ]; then
  {
    echo "# Generated by up.sh — secrets for YOUR Paperclip. Do not commit."
    echo "BETTER_AUTH_SECRET=$(openssl rand -hex 32)"
    echo "# Signs the short-lived tokens Paperclip hands each agent run. Without it"
    echo "# the starter agents cannot call back into Paperclip."
    echo "PAPERCLIP_AGENT_JWT_SECRET=$(openssl rand -hex 32)"
    echo "PAPERCLIP_TOOL_ACTION_SIGNING_SECRET=$(openssl rand -hex 32)"
    echo "PAPERCLIP_DEPLOYMENT_MODE=local_trusted"
    echo "PAPERCLIP_PUBLIC_URL=http://localhost:${PORT}"
    echo "PAPERCLIP_API_URL=http://localhost:${PORT}"
    echo "# The starter Content Drafter drafts with this. Leave blank for stub drafts."
    echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}"
  } > .env
  echo "Wrote $HERE/.env with fresh secrets."
fi
set -a; . ./.env; set +a

healthy() { curl -fsS "http://localhost:${PORT}/api/health" >/dev/null 2>&1; }

wait_up() {
  echo -n "Waiting for Paperclip"
  for _ in $(seq 1 90); do
    if healthy; then
      echo; echo "Paperclip is up at http://localhost:${PORT}"
      echo "Next: node Scripts/paperclip/bootstrap.mjs   (creates your company and starter agents)"
      return 0
    fi
    echo -n "."; sleep 2
  done
  echo; echo "Paperclip did not come up. See: ./Scripts/paperclip/up.sh logs" >&2
  return 1
}

case "${1:-up}" in
  up)
    if healthy; then echo "Paperclip is already up at http://localhost:${PORT}"; exit 0; fi
    if [ "$ENGINE" = "docker" ]; then
      command -v docker >/dev/null || { echo "Docker is not installed." >&2; exit 1; }
      PAPERCLIP_SRC="${PAPERCLIP_SRC:-$HERE/../../../paperclip}" docker compose --env-file .env up -d --build
    else
      command -v node >/dev/null || { echo "Node.js 20+ is required (https://nodejs.org). Or: PAPERCLIP_ENGINE=docker $0" >&2; exit 1; }
      # Paperclip loads ./.env from the working directory, so the secrets above
      # reach the server without touching your home directory config.
      PAPERCLIP_HOME="$HERE/data/home" nohup npx --yes paperclipai run --bind loopback >"$LOG" 2>&1 &
      echo $! > "$PIDFILE"
    fi
    wait_up
    ;;
  down)
    if [ "$ENGINE" = "docker" ]; then docker compose --env-file .env down; exit 0; fi
    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
      pkill -P "$(cat "$PIDFILE")" 2>/dev/null || true
      kill "$(cat "$PIDFILE")" 2>/dev/null || true
      rm -f "$PIDFILE"; echo "Stopped."
    else
      echo "Not running (no pid file)."
    fi
    ;;
  logs) if [ "$ENGINE" = "docker" ]; then docker compose --env-file .env logs -f; else tail -f "$LOG"; fi ;;
  status) if healthy; then echo "up at http://localhost:${PORT}"; else echo "down"; exit 1; fi ;;
  *) echo "usage: up.sh [up|down|logs|status]" >&2; exit 2 ;;
esac
